name: dotnetstrftime
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/0xNF/dart_.netstrftime
homepage: https://github.com/0xNF/dart_.netstrftime

environment:
  sdk: ^3.1.1

# Add regular dependencies here.
dependencies:
  characters: ^1.3.0
  collection: ^1.17.2
  intl: ^0.18.0
  timezone: ^0.9.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
